server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true

#management:
#  endpoints:
#    health:
#      show-details: always
#    web:
#      exposure:
#        include: health,info,prometheus
#      endpoint:
#        prometheus:
#          enabled: true

spring:
  #  security:
  #    oauth2:
  #      client:
  #        provider:
  #          petshop-realm:
  #            issuer-uri: http://localhost:7080/realms/petshop-realm
  #        registration:
  #          keycloak:
  #            provider: petshop-realm
  #            authorization-grant-type: authorization_code
  #            client-id: api-petshop
  #            client-secret: JtAUnpNKlNMno50OlxqduRr8cGhGsOqY
  #            scope: openid
  #            #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  #            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
  #      whitelist:
  #        - /actuator/prometheus
  application:
    name: dental-insurance-api
  data:
    mongodb:
      uri: mongodb+srv://melissabsouzaa:k5u2V4UYHBodQL5u@pa.tp0bwwj.mongodb.net/
      database: PA

  thymeleaf:
    encoding: UTF-8
    cache: false

  messages:
    encoding: UTF-8
    basename: messages

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    restart:
      enabled: true
  integration:
    poller:
      max-messages-per-poll:

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE